In [111]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [112]:
from sklearn import datasets
wine=datasets.load_wine()

In [113]:
wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [114]:
X=wine.data

In [115]:
Y=wine.target

In [116]:
X.shape

(178, 13)

In [117]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.30,random_state=1)

In [118]:
from sklearn.naive_bayes import GaussianNB

In [119]:
gNB=GaussianNB()
gNB.fit(X,Y)
Y_pred=gNB.predict(X)



In [120]:
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [121]:
X_test

array([[1.369e+01, 3.260e+00, 2.540e+00, 2.000e+01, 1.070e+02, 1.830e+00,
        5.600e-01, 5.000e-01, 8.000e-01, 5.880e+00, 9.600e-01, 1.820e+00,
        6.800e+02],
       [1.242e+01, 1.610e+00, 2.190e+00, 2.250e+01, 1.080e+02, 2.000e+00,
        2.090e+00, 3.400e-01, 1.610e+00, 2.060e+00, 1.060e+00, 2.960e+00,
        3.450e+02],
       [1.364e+01, 3.100e+00, 2.560e+00, 1.520e+01, 1.160e+02, 2.700e+00,
        3.030e+00, 1.700e-01, 1.660e+00, 5.100e+00, 9.600e-01, 3.360e+00,
        8.450e+02],
       [1.221e+01, 1.190e+00, 1.750e+00, 1.680e+01, 1.510e+02, 1.850e+00,
        1.280e+00, 1.400e-01, 2.500e+00, 2.850e+00, 1.280e+00, 3.070e+00,
        7.180e+02],
       [1.377e+01, 1.900e+00, 2.680e+00, 1.710e+01, 1.150e+02, 3.000e+00,
        2.790e+00, 3.900e-01, 1.680e+00, 6.300e+00, 1.130e+00, 2.930e+00,
        1.375e+03],
       [1.349e+01, 3.590e+00, 2.190e+00, 1.950e+01, 8.800e+01, 1.620e+00,
        4.800e-01, 5.800e-01, 8.800e-01, 5.700e+00, 8.100e-01, 1.820e+00,
        5.80

In [122]:
gNB.predict([[1.369e+01, 3.260e+00, 2.540e+00, 2.000e+01, 1.070e+02, 1.830e+00,
        5.600e-01, 5.000e-01, 8.000e-01, 5.880e+00, 9.600e-01, 1.820e+00,
        6.800e+02]])

array([2])

In [123]:
Y_test

array([2, 1, 0, 1, 0, 2, 1, 0, 2, 1, 0, 0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 1,
       2, 1, 0, 2, 0, 0, 0, 2, 1, 2, 2, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0,
       0, 0, 1, 0, 0, 0, 1, 2, 2, 0])

In [124]:
from sklearn.metrics import accuracy_score

In [125]:
accuracy=accuracy_score(Y,Y_pred)

In [126]:
accuracy

0.9887640449438202

# K Nearest Neighbour

## Euclidean Distance Formula
- sqrt(q1-p2)^2+(q2-p2)^2+....+(qn-pn)^2


## How does KNN works
- step1: select k no of neighbors
- step2: calculate the euclidean distance of k no of neighbors
- step3: among these k neighbors,count the no of points in each category
- step4: assign the new point to that category for which the no of neighbors is maximum

In [127]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [128]:
data=pd.read_csv("iris.csv")
data

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
5             5.4          3.9           1.7          0.4     Iris-setosa
6             4.6          3.4           1.4          0.3     Iris-setosa
7             5.0          3.4           1.5          0.2     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
9             4.9          3.1           1.5          0.1     Iris-setosa
10            5.4          3.7           1.5          0.2     Iris-setosa
11            4.8          3.4           1.6          0.2     Iris-setosa
12            4.8          3.0           1.4          0.1     Iris-setosa
13            4.3          3.0           1.1          0.1     Iris-setosa
14            5.8          4.0           1.2          0.2     Iris-setosa
15            5.7          4.4           1.5          0.4     Iris-setosa
16            5.4          3.9           1.3          0.4     Iris-setosa
17            5.1          3.5           1.4          0.3     Iris-setosa
18            5.7          3.8           1.7          0.3     Iris-setosa
19            5.1          3.8           1.5          0.3     Iris-setosa
20            5.4          3.4           1.7          0.2     Iris-setosa
21            5.1          3.7           1.5          0.4     Iris-setosa
22            4.6          3.6           1.0          0.2     Iris-setosa
23            5.1          3.3           1.7          0.5     Iris-setosa
24            4.8          3.4           1.9          0.2     Iris-setosa
25            5.0          3.0           1.6          0.2     Iris-setosa
26            5.0          3.4           1.6          0.4     Iris-setosa
27            5.2          3.5           1.5          0.2     Iris-setosa
28            5.2          3.4           1.4          0.2     Iris-setosa
29            4.7          3.2           1.6          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
120           6.9          3.2           5.7          2.3  Iris-virginica
121           5.6          2.8           4.9          2.0  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
123           6.3          2.7           4.9          1.8  Iris-virginica
124           6.7          3.3           5.7          2.1  Iris-virginica
125           7.2          3.2           6.0          1.8  Iris-virginica
126           6.2          2.8           4.8          1.8  Iris-virginica
127           6.1          3.0           4.9          1.8  Iris-virginica
128           6.4          2.8           5.6          2.1  Iris-virginica
129           7.2          3.0           5.8          1.6  Iris-virginica
130           7.4          2.8           6.1          1.9  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica
132           6.4          2.8           5.6          2.2  Iris-virginica
133           6.3          2.8           5.1          1.5  Iris-virginica
134           6.1          2.6           5.6          1.4  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
136           6.3          3.4           5.6          2.4  Iris-virginica
137           6.4          3.1           5.5          1.8  Iris-virginica
138           6.0          3.0           4.8          1.8  Iris-virginica
139           6.9          3.1           5.4          2.1  Iris-virginica
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3.1           5.1          2.3  Iris-virginica
142      

In [129]:
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [130]:
data.head(1)

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa

In [131]:
X=data[['sepal_length','sepal_width','petal_length' ,'petal_width']].values
Y=data[['species']].values

In [132]:
X,Y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [133]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.30,random_state=1)

In [134]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,Y_train)
y_pred=knn.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [135]:
y_pred

array(['Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor'], dtype=object)

In [136]:
X_test

array([[5.8, 4. , 1.2, 0.2],
       [5.1, 2.5, 3. , 1.1],
       [6.6, 3. , 4.4, 1.4],
       [5.4, 3.9, 1.3, 0.4],
       [7.9, 3.8, 6.4, 2. ],
       [6.3, 3.3, 4.7, 1.6],
       [6.9, 3.1, 5.1, 2.3],
       [5.1, 3.8, 1.9, 0.4],
       [4.7, 3.2, 1.6, 0.2],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.7, 4.2, 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [7.1, 3. , 5.9, 2.1],
       [6.4, 3.2, 4.5, 1.5],
       [6. , 2.9, 4.5, 1.5],
       [4.4, 3.2, 1.3, 0.2],
       [5.8, 2.6, 4. , 1.2],
       [5.6, 3. , 4.5, 1.5],
       [5.4, 3.4, 1.5, 0.4],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [5.4, 3. , 4.5, 1.5],
       [6.7, 3. , 5. , 1.7],
       [5. , 3.5, 1.3, 0.3],
       [7.2, 3.2, 6. , 1.8],
       [5.7, 2.8, 4.1, 1.3],
       [5.5, 4.2, 1.4, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [6.1, 2.8, 4.7, 1.2],
       [6.3, 2.5, 5. , 1.9],
       [6.1, 3. , 4.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [5.6, 2.5, 3.9, 1.1],
       [6.4, 2.8, 5.6, 2.1],
       [5.8, 2

In [137]:
#height(x1)=161
#weight(y1)=61
import math
print(math.sqrt(((161-158)**2)+((61-58)**2)))

4.242640687119285


In [138]:
data=pd.read_csv("tshirt_size.csv")
data

Height  Weight Shirt_Size
0      158      58          m
1      158      59          m
2      158      63          m
3      160      59          m
4      160      60          m
5      163      60          m
6      163      61          m
7      160      64          l
8      163      64          l
9      165      61          l
10     165      62          l
11     165      65          l
12     168      62          l
13     168      63          l
14     168      66          l
15     170      63          l
16     170      64          l
17     170      68          l

In [139]:
data.shape

(18, 3)

In [149]:
x=data.iloc[:,0:2]
y=data.iloc[:,2:]
x.head(1)
y.head(1)

Shirt_Size
0          m

In [141]:
np.ndim(x)

2

In [142]:
np.sqrt(25)

5.0

In [107]:
np.sqrt(((161-158)**2)+((61-58)**2))

4.242640687119285

In [108]:
from sklearn.neighbors import KNeighborsClassifier

In [150]:
knn2=KNeighborsClassifier(n_neighbors=5)
knn2.fit(x,y)
y_pred=knn2.predict(x)
y_pred

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


array(['m', 'm', 'm', 'm', 'm', 'm', 'l', 'm', 'l', 'l', 'l', 'l', 'l',
       'l', 'l', 'l', 'l', 'l'], dtype=object)

In [145]:
knn2.predict([[161,70]])

array(['l'], dtype=object)

# Glass classification dataset
## Attribute Information:

- Id number: 1 to 214
- RI: refractive index
- Na: Sodium (unit measurement: weight percent in corresponding oxide, as are attributes 4-10)
- Mg: Magnesium
- Al: Aluminum
- Si: Silicon
- K: Potassium
- Ca: Calcium
- Ba: Barium
- Fe: Iron
- Type of glass: (class attribute)  
  1 building_windows_float_processed  
  2 building_windows_non_float_processed 
  3 vehicle_windows_float_processed 
  4 vehicle_windows_non_float_processed (none in this database)  
  5 containers  
  6 tableware  
  7 headlamps

In [151]:
data=pd.read_csv("Glass_Classification.csv")
data

RI     Na    Mg    Al     Si     K    Ca    Ba    Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.00     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.00     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.00     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.00     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.00     1
5    1.51596  12.79  3.61  1.62  72.97  0.64  8.07  0.00  0.26     1
6    1.51743  13.30  3.60  1.14  73.09  0.58  8.17  0.00  0.00     1
7    1.51756  13.15  3.61  1.05  73.24  0.57  8.24  0.00  0.00     1
8    1.51918  14.04  3.58  1.37  72.08  0.56  8.30  0.00  0.00     1
9    1.51755  13.00  3.60  1.36  72.99  0.57  8.40  0.00  0.11     1
10   1.51571  12.72  3.46  1.56  73.20  0.67  8.09  0.00  0.24     1
11   1.51763  12.80  3.66  1.27  73.01  0.60  8.56  0.00  0.00     1
12   1.51589  12.88  3.43  1.40  73.28  0.69  8.05  0.00  0.24     1
13   1.51748  12.86  3.56  1.27  73.21  0.54  8.38  0.00  0.17     1
14   1.51763  12.61  3.59  1.31  73.29  0.58  8.50  0.00  0.00     1
15   1.51761  12.81  3.54  1.23  73.24  0.58  8.39  0.00  0.00     1
16   1.51784  12.68  3.67  1.16  73.11  0.61  8.70  0.00  0.00     1
17   1.52196  14.36  3.85  0.89  71.36  0.15  9.15  0.00  0.00     1
18   1.51911  13.90  3.73  1.18  72.12  0.06  8.89  0.00  0.00     1
19   1.51735  13.02  3.54  1.69  72.73  0.54  8.44  0.00  0.07     1
20   1.51750  12.82  3.55  1.49  72.75  0.54  8.52  0.00  0.19     1
21   1.51966  14.77  3.75  0.29  72.02  0.03  9.00  0.00  0.00     1
22   1.51736  12.78  3.62  1.29  72.79  0.59  8.70  0.00  0.00     1
23   1.51751  12.81  3.57  1.35  73.02  0.62  8.59  0.00  0.00     1
24   1.51720  13.38  3.50  1.15  72.85  0.50  8.43  0.00  0.00     1
25   1.51764  12.98  3.54  1.21  73.00  0.65  8.53  0.00  0.00     1
26   1.51793  13.21  3.48  1.41  72.64  0.59  8.43  0.00  0.00     1
27   1.51721  12.87  3.48  1.33  73.04  0.56  8.43  0.00  0.00     1
28   1.51768  12.56  3.52  1.43  73.15  0.57  8.54  0.00  0.00     1
29   1.51784  13.08  3.49  1.28  72.86  0.60  8.49  0.00  0.00     1
..       ...    ...   ...   ...    ...   ...   ...   ...   ...   ...
184  1.51115  17.38  0.00  0.34  75.41  0.00  6.65  0.00  0.00     6
185  1.51131  13.69  3.20  1.81  72.81  1.76  5.43  1.19  0.00     7
186  1.51838  14.32  3.26  2.22  71.25  1.46  5.79  1.63  0.00     7
187  1.52315  13.44  3.34  1.23  72.38  0.60  8.83  0.00  0.00     7
188  1.52247  14.86  2.20  2.06  70.26  0.76  9.76  0.00  0.00     7
189  1.52365  15.79  1.83  1.31  70.43  0.31  8.61  1.68  0.00     7
190  1.51613  13.88  1.78  1.79  73.10  0.00  8.67  0.76  0.00     7
191  1.51602  14.85  0.00  2.38  73.28  0.00  8.76  0.64  0.09     7
192  1.51623  14.20  0.00  2.79  73.46  0.04  9.04  0.40  0.09     7
193  1.51719  14.75  0.00  2.00  73.02  0.00  8.53  1.59  0.08     7
194  1.51683  14.56  0.00  1.98  73.29  0.00  8.52  1.57  0.07     7
195  1.51545  14.14  0.00  2.68  73.39  0.08  9.07  0.61  0.05     7
196  1.51556  13.87  0.00  2.54  73.23  0.14  9.41  0.81  0.01     7
197  1.51727  14.70  0.00  2.34  73.28  0.00  8.95  0.66  0.00     7
198  1.51531  14.38  0.00  2.66  73.10  0.04  9.08  0.64  0.00     7
199  1.51609  15.01  0.00  2.51  73.05  0.05  8.83  0.53  0.00     7
200  1.51508  15.15  0.00  2.25  73.50  0.00  8.34  0.63  0.00     7
201  1.51653  11.95  0.00  1.19  75.18  2.70  8.93  0.00  0.00     7
202  1.51514  14.85  0.00  2.42  73.72  0.00  8.39  0.56  0.00     7
203  1.51658  14.80  0.00  1.99  73.11  0.00  8.28  1.71  0.00     7
204  1.51617  14.95  0.00  2.27  73.30  0.00  8.71  0.67  0.00     7
205  1.51732  14.95  0.00  1.80  72.99  0.00  8.61  1.55  0.00     7
206  1.51645  14.94  0.00  1.87  73.11  0.00  8.67  1.38  0.00     7
207  1.51831  14.39  0.00  1.82  72.86  1.41  6.47  2.88  0.00     7
208  1.51640  14.37  0.00  2.74  72.85  0.00  9.45  0.54  0.00     7
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.00     7
210  1.5