## Confusion Matrix
- a confusion matrix is a table that often used to describe the performance of classification model

## Random Forest
- collection of decision trees is called a Random forest
- It plays a key role for 1 lakh column of dataset
- Random forest is applicable both classification and regression


In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [41]:
data=pd.read_csv("diabates.csv")
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
5              5      116             74              0        0  25.6   
6              3       78             50             32       88  31.0   
7             10      115              0              0        0  35.3   
8              2      197             70             45      543  30.5   
9              8      125             96              0        0   0.0   
10             4      110             92              0        0  37.6   
11            10      168             74              0        0  38.0   
12            10      139             80              0        0  27.1   
13             1      189             60             23      846  30.1   
14             5      166             72             19      175  25.8   
15             7      100              0              0        0  30.0   
16             0      118             84             47      230  45.8   
17             7      107             74              0        0  29.6   
18             1      103             30             38       83  43.3   
19             1      115             70             30       96  34.6   
20             3      126             88             41      235  39.3   
21             8       99             84              0        0  35.4   
22             7      196             90              0        0  39.8   
23             9      119             80             35        0  29.0   
24            11      143             94             33      146  36.6   
25            10      125             70             26      115  31.1   
26             7      147             76              0        0  39.4   
27             1       97             66             15      140  23.2   
28            13      145             82             19      110  22.2   
29             5      117             92              0        0  34.1   
..           ...      ...            ...            ...      ...   ...   
738            2       99             60             17      160  36.6   
739            1      102             74              0        0  39.5   
740           11      120             80             37      150  42.3   
741            3      102             44             20       94  30.8   
742            1      109             58             18      116  28.5   
743            9      140             94              0        0  32.7   
744           13      153             88             37      140  40.6   
745           12      100             84             33      105  30.0   
746            1      147             94             41        0  49.3   
747            1       81             74             41       57  46.3   
748            3      187             70             22      200  36.4   
749            6      162             62              0        0  24.3   
750            4      136             70              0        0  31.2   
751            1      121             78             39       74  39.0   
752            3      108             62             24        0  26.0   
753            0      181             88             44      510  43.3   
754            8      154             78             32        0  32.4   
755            1      128             88             39      110  36.5   
756            7      137             90             41        0  32.0   
757            0      123             72              0        0  36.3   
758            1      106             76              0        0  37.5   
759            6      190             92              0        0  35.5   
760      

In [42]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [43]:
data.shape

(768, 9)

In [44]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [45]:
X= data.drop('Outcome',axis=1)
Y= data['Outcome']

In [46]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.30,random_state=1)

In [47]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train,Y_train)
y_pred=rf.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [48]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [49]:
X_test

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
285            7      136             74             26      135  26.0   
101            1      151             60              0        0  26.1   
581            6      109             60             27        0  25.0   
352            3       61             82             28        0  34.4   
726            1      116             78             29      180  36.1   
472            0      119             66             27        0  38.8   
233            4      122             68              0        0  35.0   
385            1      119             54             13       50  22.3   
556            1       97             70             40        0  38.1   
59             0      105             64             41      142  41.5   
756            7      137             90             41        0  32.0   
341            1       95             74             21       73  25.9   
445            0      180             78             63       14  59.4   
614           11      138             74             26      144  36.1   
371            0      118             64             23       89   0.0   
355            9      165             88              0        0  30.4   
19             1      115             70             30       96  34.6   
711            5      126             78             27       22  29.6   
430            2       99              0              0        0  22.2   
117            5       78             48              0        0  33.7   
493            4      125             70             18      122  28.9   
218            5       85             74             22        0  29.0   
159           17      163             72             41      114  40.9   
667           10      111             70             27        0  27.5   
553            1       88             62             24       44  29.9   
628            5      128             80              0        0  34.6   
620            2      112             86             42      160  38.4   
238            9      164             84             21        0  30.8   
640            0      102             86             17      105  29.3   
750            4      136             70              0        0  31.2   
..           ...      ...            ...            ...      ...   ...   
160            4      151             90             38        0  29.7   
714            3      102             74              0        0  29.5   
372            0       84             64             22       66  35.8   
14             5      166             72             19      175  25.8   
612            7      168             88             42      321  38.2   
119            4       99             76             15       51  23.2   
82             7       83             78             26       71  29.3   
373            2      105             58             40       94  34.9   
375           12      140             82             43      325  39.2   
353            1       90             62             12       43  27.2   
107            4      144             58             28      140  29.5   
17             7      107             74              0        0  29.6   
323           13      152             90             33       29  26.8   
172            2       87              0             23        0  28.9   
402            5      136             84             41       88  35.0   
366            6      124             72              0        0  27.6   
103            1       81             72             18       40  26.6   
422            0      102             64             46       78  40.6   
301            2      144             58             33      135  31.6   
396            3       96             56             34      115  24.7   
697            0       99              0              0        0  25.0   
432            1       80             74             11       60  30.0   
45       

In [29]:
X_test[:5]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
285            7      136             74             26      135  26.0   
101            1      151             60              0        0  26.1   
581            6      109             60             27        0  25.0   
352            3       61             82             28        0  34.4   
726            1      116             78             29      180  36.1   

     DiabetesPedigreeFunction  Age  
285                     0.647   51  
101                     0.179   22  
581                     0.206   27  
352                     0.243   46  
726                     0.496   25

In [50]:
rf.predict([[7,136,74,26,135,26.0,0.647,51]])

array([0], dtype=int64)

In [51]:
Y_test[:5]

285    0
101    0
581    0
352    0
726    0
Name: Outcome, dtype: int64

In [52]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test,y_pred))

[[131  15]
 [ 34  51]]


In [53]:
from sklearn.metrics import accuracy_score

In [55]:
accuracy=accuracy_score(Y_test,y_pred)

In [56]:
accuracy

0.7878787878787878

# Classification Report
- precision: what percentage of your preditions were correct
      - precision= TP/(TP+FP)
- recall: what percentage of positive cases you got
      - Recall= TP/(TP+FP)
- F1 score: what percentage of positive predictions were correct 
      - F1 score= (2*(Recall* precision))/(Recall+precision)

In [58]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.90      0.84       146
           1       0.77      0.60      0.68        85

   micro avg       0.79      0.79      0.79       231
   macro avg       0.78      0.75      0.76       231
weighted avg       0.79      0.79      0.78       231



In [59]:
import seaborn as sns

In [60]:
corr =data.corr()
corr

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000

In [ ]:
sns.heatmap(corr,)